# Generated by Django 5.1.2 on 2024-12-12 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_remove_event_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='choice_text',
            field=models.CharField(default='test', max_length=200),
        ),
    ]
